---
kind: pipeline
name: analyse

steps:
  - name: sonar
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host: https://sonar.castive.dev
      sonar_token:
        from_secret: SONAR_TOKEN