version: '3'
services:
  crowd:
    image: dchevell/crowd:3.5.0-alpine
    container_name: crowd
    volumes:
      - ./crowd:/var/atlassian/application-data/crowd
    ports:
      - 8095:8095
  ldap:
    image: osixia/openldap:1.3.0
    command: ["--copy-service"]
    ports:
      - 389:389
    environment:
      - LDAP_TLS=false
    volumes:
      - ldap:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - ldap
  ldap-ui:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - 8080:80
    depends_on:
      - ldap
    networks:
      - ldap

networks:
  ldap:
volumes:
  ldap:
  ldap_config: